#ifndef _LANGUAGE_H_
#define _LANGUAGE_H_
#include "user_monitor.h"

typedef enum
{
	LANG_ENGLISH = 0,
	LANG_PERSIAN,
	LANG_TOTAL
} language_type;

typedef enum
{
	// layout home
	LAYOUT_HOME_LANG_DOOR1_ID,
	LAYOUT_HOME_LANG_DOOR2_ID,
	LAYOUT_HOME_LANG_CCTV1_ID,
	LAYOUT_HOME_LANG_CCTV2_ID,
	LAYOUT_HOME_LANG_LANGUAGE_ID,
	LAYOUT_HOME_LANG_BELL_ID,
	LAYOUT_HOME_LANG_RECORD_ID,
	LAYOUT_HOME_LANG_LOCK_ID,
	LAYOUT_HOME_LANG_ID_WEEK_1,
	LAYOUT_HOME_LANG_ID_WEEK_2,
	LAYOUT_HOME_LANG_ID_WEEK_3,
	LAYOUT_HOME_LANG_ID_WEEK_4,
	LAYOUT_HOME_LANG_ID_WEEK_5,
	LAYOUT_HOME_LANG_ID_WEEK_6,
	LAYOUT_HOME_LANG_ID_WEEK_7,
	LAYOUT_HOME_LANG_MINOTOR_ID,
	LAYOUT_HOME_LANG_CCTV_ID,
	COMMON_LANG_SECURITY_ID,
	LAYOUT_HOME_LANG_ELEVATOR_ID,

	// layout camera
	LAYOUT_CAMERA_LANG_BRIGHTNESS_ID,
	LAYOUT_CAMERA_LANG_COLOR_ID,
	LAYOUT_CAMERA_LANG_CONTRAST_ID,
	LAYOUT_CAMERA_LANG_CAM1_2_ID,
	LAYOUT_CAMERA_LANG_CHANGE_ID,
	LAYOUT_CAMERA_LANG_ZOOM_ID,
	LAYOUT_CAMERA_LANG_OPEN_ID,
	LAYOUT_CAMERA_LANG_RECORD_IMAGE_ID,
	LAYOUT_CAMERA_LANG_RECORD_VIDEO_ID,
	LAYOUT_CAMERA_LANG_SECOND_ID,
	LAYOUT_CAMERA_LANG_DOOR_OPEN_ID,

	// layout language
	LAYOUT_LANGUAGE_LANG_SELECT_ID,
	LAYOUT_LANGUAGE_LANG_ENGLISH_ID,
	LAYOUT_LANGUAGE_LANG_PERSIAN_ID,

	// layout bell
	LAYOUT_BELL_LANG_BELL_VOL_ID,
	LAYOUT_BELL_LANG_DOOR1_RING_ID,
	LAYOUT_BELL_LANG_DOOR2_RING_ID,
	LAYOUT_BELL_LANG_RING_ID,

	// layout calendar
	LAYOUT_CALENDAR_LANG_TIME_DISPLAY_ID,
	LAYOUT_CALENDAR_LANG_CLOCK_STYLE_ID,
	LAYOUT_CALENDAR_LANG_PERSIAN_ID,
	LAYOUT_CALENDAR_LANG_WEATERN_ID,
	LAYOUT_CALENDAR_LANG_YEAR_ID,
	LAYOUT_CALENDAR_LANG_MONTH_ID,
	LAYOUT_CALENDAR_LANG_DAY_ID,
	LAYOUT_CALENDAR_LANG_HOUR_ID,
	LAYOUT_CALENDAR_LANG_MIN_ID,

	// layout memory
	LAYOUT_MEMORY_LANG_IMAGE_ID,
	LAYOUT_MEMORY_LANG_IMAGE_LISE_ID,
	LAYOUT_MEMORY_LANG_VIDEO_ID,
	LAYOUT_MEMORY_LANG_VIDEO_LISE_ID,
	LAYOUT_MEMORY_LANG_MODE_ID,
	LAYOUT_MEMORY_LANG_PREV_ID,
	LAYOUT_MEMORY_LANG_PLAY_ID,
	LAYOUT_MEMORY_LANG_STOP_ID,
	LAYOUT_MEMORY_LANG_NEXT_ID,
	LAYOUT_MEMORY_LANG_DELETE_VIDEO_ID,
	LAYOUT_MEMORY_LANG_DELETE_PICTURE_ID,
	LAYOUT_MEMORY_LANG_DELETE_ALL_VIDEO_ID,
	LAYOUT_MEMORY_LANG_DELETE_ALL_PICTURE_ID,
	LAYOUT_MEMORY_LANG_DELETE_ALL_CALL_ID,
	// layout recording
	LAYOUT_MEMORY_LANG_NO_IMAGE_ID,
	LAYOUT_MEMORY_LANG_NO_VIDEO_ID,
	LAYOUT_MEMORY_LANG_NO_SD_ID,
	LAYOUT_MEMORY_LANG_CALL_ID,
	LAYOUT_MEMORY_LANG_RECORD_TIME_ID,
	LAYOUT_MEMORY_LANG_DEVICE_ID,
	LAYOUT_MEMORY_LANG_RECORD_MODE_ID,
	LAYOUT_MEMORY_LANG_CALL_TIME_ID,
	LAYOUT_MEMORY_LANG_STATE_ID,
	LAYOUT_MEMORY_LANG_MANUAL_ID,
	LAYOUT_MEMORY_LANG_AUTO_ID,
	LAYOUT_MEMORY_LANG_MOTION,
	LAYOUT_MEMORY_LANG_REJECT_ID,
	LAYOUT_MEMORY_LANG_ANSWERED_ID,

	// layout security
	LAYOUT_SECURITY_LANGUAGE_ID_SECURITY,
	LAYOUT_SECURITY_LANGUAGE_ID_AUTO_REC,
	LAYOUT_SECURITY_LANGUAGE_ID_SENSOR_1_ERROR,
	LAYOUT_SECURITY_LANGUAGE_ID_SENSOR_2_ERROR,
	LAYOUT_SECURITY_LANGUAGE_ID_SENSOR_1,
	LAYOUT_SECURITY_LANGUAGE_ID_SENSOR_2,
	LAYOUT_SECURITY_LANGUAGE_ID_SENSOR_WORKING,
	LAYOUT_SECURITY_LANGUAGE_ID_SENSOR_1_AND_2_ERROR,
	SENSOR_NOT_SELECTED,
	LAYOUT_SECURITY_LANGUAGE_ID_EXE,
	LAYOUT_SECURITY_LANGUAGE_ID_END,
	PLEASE_CHECK_SENSOR_STATE,

	// layout alarm_list
	LAN_DELETE_FILE,
	LAYOUT_SECURITY_LANGUAGE_ID_SECURITY_EMERGENCY_1,
	LAYOUT_SECURITY_LANGUAGE_ID_SECURITY_EMERGENCY_2,
	LAYOUT_SECURITY_LANGUAGE_ID_EMERITY_RECORD,

	// layout motion_detection
	LAYOUT_MOTION_DETECTION_LOW_ID,
	LAYOUT_MOTION_DETECTION_MIDDLE_ID,
	LAYOUT_MOTION_DETECTION_HIGH_ID,
	// layout intercom
	SETTING_LANG_ID_ROOM_ID1,
	SETTING_LANG_ID_ROOM_ID2,
	SETTING_LANG_ID_ROOM_ID3,
	SETTING_LANG_ID_ROOM_ID4,
	LAYOUT_INTERCOM_LANG_LOCAL_ADDR_ID,
	LAYOUT_INTERCOM_LANG_INPUT_ROOM_NO_ID,
	LAYOUT_INTERCOM_LANG_SET_OK_ID,
	LAYOUT_INTERCOM_LANG_INTERCOM_RECEIVE_ID,
	LAYOUT_INTERCOM_LANG_CALL_NUMBER_ID,
	LAYOUT_INTERCOM_LANG_INPUT_PASSWORD_ID,
	LAYOUT_INTERCOM_LANG_GUARD_ID,
	LAYOUT_INTERCOM_LANG_GUARD_1_ID,
	LAYOUT_INTERCOM_LANG_GUARD_2_ID,
	LAYOUT_INTERCOM_LANG_OK_ID,
	LAYOUT_INTERCOM_LANG_TAKE_HANDSET_ID,
	LAYOUT_INTERCOM_LANG_LOCAL_ID,
	LAYOUT_INTERCOM_LANG_CALLING_ID,
	LAYOUT_INTERCOM_LANG_BUS_BUSY_ID,
	LAYOUT_INTERCOM_LANG_UNIT_BUSY_ID,
	LAYOUT_INTERCOM_LANG_NO_RESPONSE_ID,
	LAYOUT_INTERCOM_LANG_ERROR_ID,

	LAYOUT_INTERCOM_LANG_RING_VOL_ID,
	LAYOUT_INTERCOM_LANG_RING2_VOL_ID,
	LAYOUT_INTERCOM_LANG_RINGING_FROM_ID,
	LAYOUT_INTERCOM_LANG_CALLING_TO_ID,
	LAYOUT_INTERCOM_LANG_TALKING_WITH_ID,
	LAYOUT_INTERCOM_LANG_DISCONNECT_ID,
	LAYOUT_INTERCOM_LANG_END_ID,
	LAYOUT_INTERCOM_LANG_NO_ANSWER_ID,
	LAYOUT_INTERCOM_LANG_ROOM_NO_ID,

	// layout setting
	LAYOUT_SETTING_LANG_ROOM_NO_SETTING_ID,
	LAYOUT_SETTING_LANG_ROOM_ID,
	LAYOUT_SETTING_LANG_SD_CARD_ID,
	LAYOUT_SETTING_LANG_RESET_ID,
	LAYOUT_SETTING_LANG_ABOUT_ID,
	LAYOUT_SETTING_LANG_SYSTEM_ID,
	LAYOUT_SETTING_LANG_TIME_ID,
	LAYOUT_SETTING_LANG_SOUND_ID,
	LAYOUT_SETTING_LANG_SECUTITY_PASSWORD_ID,
	LAYOUT_SETTING_LANG_FACTORY_SER_ID,
	LAYOUT_SETTING_LANG_FORMAT_ID,
	LAYOUT_SETTING_BACKUP_PHOTOS_SD_ID,
	LAYOUT_SETTING_LANG_MOTION_DETECTION_ID,
	LAYOUT_SETTING_LANG_SCREEN_ADJUST_ID,
	LAYOUT_SETTING_LANG_SYSTEM_KEYTONE_ID,

	LAYOUT_SETTING_LANG_SONG_ID,
	LAYOUT_SETTING_LANG_SONG2_ID,

	LAYOUT_INTERCOM_LANG_RING_VOL_SET_ID,
	LAYOUT_SETTING_LANG_CALL_VOL_SET_ID,
	LAYOUT_SETTING_LANG_CALL_VOL_ID,
	LAYOUT_SETTING_LANG_OFF_ID,
	LAYOUT_SETTING_LANG_ON_ID,
	LAYOUT_SETTING_FACTORY_RESET_ID,
	LAYOUT_SETTING_FORMAT_SD_ID,
	LAYOUT_SETTING_BACKUP_PHOTOS_SD_ICON_ID,

	// layout setting password
	SETTING_PASSWORD_LANG_ID_ENTER_PWD,
	THE_PWD_TOO_SIMPLE,
	THE_PWD_NOT_MATCH,
	SETTING_PASSWORD_LANG_ID_PWD_RESET,
	SETTING_PASSWORD_LANG_ID_NEW_PWD,
	SETTING_PASSWORD_LANG_ID_CONFIRM_PWD,
	SETTING_PASSWORD_LANG_ID_APPLE,

	// layout setting detection
	LAYOUT_SET_DETECTIONG_OPEN_DETECTION_ID,
	LAYOUT_SET_DETECTIONG_CAMERA_SELECT_ID,
	LAYOUT_SET_DETECTIONG_STORAGE_MODE_ID,
	LAYOUT_SET_DETECTIONG_SENSITIVITY_ID,
	LAYOUT_SET_DETECTIONG_RECORD_DURATION_ID,
	LAYOUT_SET_DETECTIONG_BRIGHT_SCREEN_ID,
	LAYOUT_SET_DETECTIONG_TIME_PETIOD_COUNT_ID,

	// layout record
	LAYOUT_RECORD_LANG_AUTO_RECORD_ID,
	LAYOUT_RECORD_LANG_RECORD_MODE_ID,
	LAYOUT_RECORD_LANG_IMAGE_ID,
	LAYOUT_RECORD_LANG_VIDEO_ID,
	LAYOUT_RECORD_LANG_PLEASE_INSERT_SD,

	// layout room id
	LAYOUT_ROOM_ID_LANG_ROOM_ID_ID,
	LAYOUT_ROOM_ID_LANG_MODIFY_SUCCESSFUL_ID,

	// layout delete
	LAYOUT_DELETE_LANG_ALL_PICTURES_ID,
	LAYOUT_DELETE_LANG_ALL_VIDEOS_ID,
	LAYOUT_DELETE_LANG_DELETING_ID,

	// layout sd card
	LAYOUT_SD_LANG_COPY_ID,
	LAYOUT_SD_LANG_COPYING_ID,
	LAYOUT_SD_LANG_FORMAT_ID,
	LAYOUT_SD_LANG_FORMATING_ID,
	LAYOUT_SD_LANG_FORMAT_OK_ID,

	// layout reset
	LAYOUT_RESET_LANG_FACTORY_ID,

	// layout about
	LAYOUT_ABOUT_LANG_TABA_ID,
	LAYOUT_ABOUT_LANG_MODEL_ID,
	LAYOUT_ABOUT_LANG_VERSION_ID,

	// common
	COMMON_LANG_HOME_ID,
	COMMON_LANG_CALENDAR_ID,
	COMMON_LANG_INTERCOM_ID,
	COMMON_LANG_SETTING_ID,
	COMMON_LANG_EXIT_ID,
	COMMON_LANG_CAM1_ID,
	COMMON_LANG_CAM2_ID,
	COMMON_LANG_RECORD_ID,
	COMMON_LANG_DELETE_ID,
	COMMON_LANG_BACK_ID,
	COMMON_LANG_YES_ID,
	COMMON_LANG_NO_ID,
	COMMON_LANG_CONFIRM_ID,
	COMMON_LANG_NO_SD_ID,

	COMMON_LANG_RETURN_ID,

	// COMMON_LANG_ZERO_ID,

	LANG_STR_ID_TOTAL,
} layout_lang_id;

const char *str_get(layout_lang_id id);

#endif